graphQLEntryPoint:
  path: /api/graphql
  controller: App\Controller\GraphEntryController::graphQLEntryPoint
  methods: POST
login_check:
  path:     /api/login_check
  methods:  [POST]
register:
  path: /user/register
  methods: [POST]
  controller: App\Controller\UserController::registerUserAction
