graphQLEntryPoint:
  path: /api/graphql
  controller: App\Controller\GraphEntryController::graphQLEntryPoint
  methods: POST
login_check:
  path:     /api/login_check
  methods:  [POST]
register:
  path: /api/user/register
  methods: [POST]
  controller: App\Controller\UserController::registerUserAction
account_confirmation:
  path: /api/user/confirm-email
  methods: [PUT]
  controller: App\Controller\AccountConfirmationController::confirmAccountWithTokenAction
