graphQLEntryPoint:
  path: /api/graphql
  controller: App\Controller\GraphEntryController::graphQLEntryPoint
  methods: POST
login_check:
  path:     /api/login_check
  methods:  [POST]
register:
  path: /api/user/register
  methods: [POST]
  controller: App\Controller\UserController::registerUserAction
account_confirmation:
  path: /api/user/confirm-email
  methods: [PUT]
  controller: App\Controller\AccountConfirmationController::confirmAccountWithTokenAction
gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
send_message_mercure:
  path:       /api/message/{user}
  controller: App\Controller\MessengerController::sendMessageAction
